plugins:
  - bsmu.vision.plugins.windows.main.MainWindowPlugin
  - bsmu.vision.plugins.file_dropper.FileDropperPlugin
  - bsmu.vision.plugins.loaders.image.simple.SimpleImageFileLoaderPlugin
#  - bsmu.vision.plugins.loaders.image.wsi.WholeSlideImageFileLoaderPlugin
#  - bsmu.vision.plugins.loaders.nifti.base.NiftiFileLoaderPlugin
  - bsmu.vision.plugins.post_load_converters.image_to_layered.ImageToLayeredImagePostLoadConverterPlugin
  - bsmu.vision.plugins.visualizers.image.flat.FlatImageVisualizerPlugin
#  - bsmu.vision.plugins.visualizers.image.volume.VolumeImageVisualizerPlugin
  - bsmu.vision.plugins.visualizers.image.layered.LayeredImageVisualizerPlugin
  - bsmu.vision.plugins.overlayers.image.base.ImageViewerOverlayerPlugin
  - bsmu.vision.plugins.overlayers.path.ImageViewerPathOverlayerPlugin
#  - bsmu.vision.plugins.overlayers.intersection.ImageViewerIntersectionOverlayerPlugin
  - bsmu.vision.plugins.writers.image.generic.GenericImageFileWriterPlugin
  - bsmu.vision.plugins.layouts.base.MdiLayoutPlugin
  - bsmu.vision.plugins.walkers.file.MdiImageLayerFileWalkerPlugin
#  - bsmu.vision.plugins.walkers.slice.MdiVolumeSliceWalkerPlugin
#  - bsmu.vision.plugins.tools.viewer.image.smart_brush.SmartBrushImageViewerToolPlugin
  - bsmu.vision.plugins.tools.viewer.image.wsi_smart_brush.WsiSmartBrushImageViewerToolPlugin
  - bsmu.vision.plugins.layer_controller.MdiImageViewerLayerControllerPlugin
  - bsmu.vision.plugins.layers_view.LayersTableViewPlugin

enable-gui: true

max_general_thread_count: null  # If null, then `QThread.idealThreadCount() - max_dnn_thread_count` will be used
max_dnn_thread_count: 1

warn-with-traceback: false

onnx_providers:
  - CUDAExecutionProvider
  - CPUExecutionProvider

opencv_io_max_pixels: 10995116277760000