plugins:
  - bsmu.vision.plugins.windows.main.MainWindowPlugin
  - bsmu.vision.plugins.layouts.mdi.MdiLayoutPlugin

  - bsmu.vision.plugins.file_dropper.FileDropperPlugin
  - bsmu.vision.plugins.readers.image.common.CommonImageFileReaderPlugin
#  - bsmu.vision.plugins.readers.image.wsi.WholeSlideImageFileReaderPlugin
#  - bsmu.vision.plugins.readers.nifti.NiftiFileReaderPlugin

  - bsmu.vision.plugins.postread.image_to_layered.ImageToLayeredImagePostReadConverterPlugin

  - bsmu.vision.plugins.visualizers.image.flat.FlatImageVisualizerPlugin
#  - bsmu.vision.plugins.visualizers.image.volume.VolumeImageVisualizerPlugin
  - bsmu.vision.plugins.visualizers.image.layered.LayeredImageVisualizerPlugin

  - bsmu.vision.plugins.overlayers.image.ImageViewerOverlayerPlugin
  - bsmu.vision.plugins.overlayers.path.ImageViewerPathOverlayerPlugin
#  - bsmu.vision.plugins.overlayers.intersection.ImageViewerIntersectionOverlayerPlugin

  - bsmu.vision.plugins.writers.image.common.CommonImageFileWriterPlugin

  - bsmu.vision.plugins.tools.viewer.manager.ViewerToolManagerPlugin
  - bsmu.vision.plugins.tools.viewer.image.hand_tool.HandImageViewerToolPlugin
#  - bsmu.vision.plugins.tools.viewer.image.smart_brush.SmartBrushImageViewerToolPlugin
  - bsmu.vision.plugins.tools.viewer.image.wsi_smart_brush.WsiSmartBrushImageViewerToolPlugin
#  - bsmu.vision.plugins.tools.viewer.polyline.PolylineViewerToolPlugin

  - bsmu.vision.plugins.walkers.file.MdiImageLayerFileWalkerPlugin
#  - bsmu.vision.plugins.walkers.slice.MdiVolumeSliceWalkerPlugin

  - bsmu.vision.plugins.layer_controller.MdiImageViewerLayerControllerPlugin
  - bsmu.vision.plugins.layers_view.LayersTableViewPlugin

  - bsmu.vision.plugins.task_storage_view.TaskStorageViewPlugin

enable_gui: true

max_general_thread_count: null  # If null, then `QThread.idealThreadCount() - max_dnn_thread_count` will be used
max_dnn_thread_count: 1

warn_with_traceback: false

onnx_providers:
  - CUDAExecutionProvider
  - CPUExecutionProvider

opencv_io_max_image_pixels: 1_099_511_627_776  # 1 TB = 2 ^ 40 bytes
