layers:
  image: 'active_layer'
#    name: 'images'
#    number: 0
  mask:
    # If the active layer is indexed, then it's used as mask layer
    use_active_indexed_layer: true
    # Use the first found indexed layer as mask layer
    use_first_indexed_layer: true
    name: 'masks'
    # Next properties will be used, if there is no mask, and we have to create one
    palette: null  # if null, then default palette will be used
    opacity: 0.5
  tool_mask:
    name: 'tool-mask'
    # Next properties will be used, if we have to create new tool mask
    palette:
      row-by-name:
        background: [ 0, 0, 0, 0, 0 ]
        foreground: [ 1, 130, 210, 50, 255 ]  # tool region, where mask will be painted, if tool is used
        eraser: [ 2, 210, 60, 40, 255 ]  # tool region, where mask will be erased, if tool is used
        unconnected_component: [ 3, 210, 130, 50, 255 ]  # tool region, where mask will not be painted if tool is used,
        # because it is an isolated region
        no_paint: [ 4, 0, 0, 0, 63 ]  # tool region, where mask will not be painted, if tool is used
    opacity: 0.5
