radius: 50
min_radius: 2
max_radius: 400
radius_zoom_factor: 1
max_radius_without_downscale: 150
downscale_factor: 1  # (0; 1]

smart_mode_enabled: true

repainting:
  enabled: true
  mode: 'all'  # Options:
               # 'all' (repaint all classes),
               # 'pointer' (repaint the class under the mouse pointer),
               # 'custom' (repaint a custom class)
  custom_class: 1  # Only relevant if mode is 'custom'

number_of_clusters: 2
painted_cluster: 'central'  # Options: 'dark', 'medium', 'light', 'central' (under mouse pointer),
  # or a cluster index based on brightness (0 - darkest, (number_of_clusters - 1) - lightest)
paint_connected_component: true

draw_on_mouse_move: true
