main_palette:
  default_color: [ 50, 0, 50, 255 ]
  row_by_name:
    background: [   0,   0,   0,   0,   0 ]
    foreground: [   1,  50, 170, 230, 255 ]
    class_2:    [   2, 230, 218,  50, 255 ]
    class_3:    [   3, 146,  50, 230, 255 ]
    class_4:    [   4, 230,  50,  98, 255 ]
    class_5:    [   5,  50, 205,  50, 255 ]
    class_6:    [   6, 230, 110,  50, 255 ]
    class_7:    [   7,  50, 230, 182, 255 ]
    class_8:    [   8,  50,  62, 230, 255 ]

risk_palette:
  default_color: [ 50, 0, 50, 255 ]
  row_by_name:
    background: [   0,   0,   0,   0,   0 ]
    foreground: [   1,  50, 205,  50, 255 ]  # Green
    yellow:     [   2, 230, 218,  50, 255 ]
    orange:     [   3, 230, 110,  50, 255 ]
    red:        [   4, 230,  50,  98, 255 ]
    light_blue: [   5,  50, 170, 230, 255 ]
    blue:       [   6,  50,  62, 230, 255 ]
    purple:     [   7, 146,  50, 230, 255 ]
