radius: 50
min_radius: 2
max_radius: 400
radius_zoom_factor: 1
max_radius_without_downscale: 150
downscale_factor: 1  # (0; 1]

smart_mode_enabled: true

repainting_enabled: true

number_of_clusters: 2
paint_central_pixel_cluster: true
paint_dark_cluster: false
paint_connected_component: true

draw_on_mouse_move: true
