plugins:
  - bsmu.bone_age.plugins.main_window.BoneAgeMainWindowPlugin -> bsmu.vision.plugins.windows.main.MainWindowPlugin
#  - mdi_plugin = bsmu.vision.plugins.doc_interfaces.mdi.MdiPlugin(main_window_plugin)
#  - bsmu.vision.plugins.file_dropper.FileDropperPlugin(mdi_plugin)
  - bsmu.vision.plugins.file_dropper.FileDropperPlugin

  - bsmu.vision.plugins.loaders.image.simple.SimpleImageFileLoaderPlugin
  - bsmu.vision.plugins.loaders.dicom.multi_frame.MultiFrameDicomFileLoaderPlugin
  - bsmu.vision.plugins.loaders.nifti.base.NiftiFileLoaderPlugin
  - bsmu.vision.plugins.visualizers.image.flat.FlatImageVisualizerPlugin
  - bsmu.vision.plugins.visualizers.image.volume.VolumeImageVisualizerPlugin
  - bsmu.vision.plugins.visualizers.image.layered.LayeredImageVisualizerPlugin
#  - bsmu.vision.plugins.walkers.file.MdiImageLayerFileWalkerPlugin
##  - bsmu.vision.plugins.walkers.slice.MdiVolumeSliceWalkerPlugin
#  - bsmu.vision.plugins.overlayers.path.ImageViewerPathOverlayerPlugin
#  - bsmu.vision.plugins.layer_controller.MdiImageViewerLayerControllerPlugin
##  - bsmu.vision.plugins.tools.viewer.image.smart_brush.SmartBrushImageViewerToolPlugin
  - bsmu.vision.plugins.post_load_converters.image_to_layered.ImageToLayeredImagePostLoadConverterPlugin
##  - bsmu.vision.plugins.layouts.base.MdiLayoutPlugin
##  - bsmu.vision.plugins.color_contrast.ColorContrastPlugin
#
  - bsmu.bone_age.plugins.table_visualizer.BoneAgeTableVisualizerPlugin
  - bsmu.bone_age.plugins.atlas_visualizer.BoneAgeAtlasVisualizerPlugin
  - bsmu.bone_age.plugins.journal_exporter.PatientBoneAgeJournalExporterPlugin
  - bsmu.bone_age.plugins.image_loader.ImageLoaderPlugin
